### ISSUE TITLE
Mattermost API v3 Deprecated - No Support for V4 

### ISSUE THREAD

**Issue by boutikcircus-paaf** [meetfranz/recipe-mattermost#1]
It seems that MM has deprecated V3 of the API and the new version is not compatible with the current plugin.

{"id":"api.context.v3_disabled.app_error","message":"API version 3 has been disabled on this server. Please use API version 4. See https://api.mattermost.com for details.","detailed_error":"","request_id":"1hpk94jsjtrxukeokgiqws88je","status_code":501}

**Comment by adlk** [comment]
Fixed in 4412bf3448742a2f9b1c49d56d970c9f9aa27837
